<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-2D2CTMR" name="sampletest.InvokationTimeOutTest" tests="1" failures="0" timestamp="18 Mar 2018 06:06:44 GMT" time="5.022" errors="1">
  <testcase name="loginTest" time="5.022" classname="sampletest.InvokationTimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method sampletest.InvokationTimeOutTest.loginTest() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method sampletest.InvokationTimeOutTest.loginTest() didn't finish within the time-out 5000
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- loginTest -->
</testsuite> <!-- sampletest.InvokationTimeOutTest -->
